trigger:
  branches:
    include:
      - "master"

parameters:
  - name: s3Bucket
    displayName: "S3 bucket Name"
    type: string
    default: "sweepstake-helpfile"

pool:
  name: RCT.Build.Agent.Pool-01
  demands:
    - sh

variables:
  - group: PipelineBasicVariables

steps:
  # upload file to AWS S3
  - script: |
      aws s3 cp $(Build.SourcesDirectory)/docs/ s3://${{ parameters.s3Bucket }}/docs/ --recursive
    displayName: "Upload File to S3"
    env:
      AWS_ACCESS_KEY_ID: $(AwsAccessKeyId)
      AWS_SECRET_ACCESS_KEY: $(AwsSecretAccessKey)
      AWS_DEFAULT_REGION: "ap-northeast-1"
